version: "3.9"
services:
  api:
    build:
      context: ./api
    image: bank-api:latest
    container_name: bank_api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/best_model_pipeline.joblib
    volumes:
      - ../../models:/app/models:ro

  app:
    build:
      context: ./app
    image: bank-app:latest
    container_name: bank_app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000  
    depends_on:
      - api
